version: '3'
services:
  mysql-db:
    image: mysql:latest
    hostname: gf-mysql-db
    container_name: gf-mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'gofound'
      MYSQL_USER: 'web'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db-volume:/var/lib/mysql
volumes:
  my-db-volume: